//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaleFashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public int MaBV { get; set; }
        public string TenBV { get; set; }
        public string NoiDung { get; set; }
        public string NoiDungTT { get; set; }
        public string HinhAnh { get; set; }
        public string LoaiTin { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<bool> DaDuyet { get; set; }
        public Nullable<int> MaTK { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
