//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaleFashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDonHang
    {
        public int MaCTDH { get; set; }
        public int MaDH { get; set; }
        public string MaSP { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public decimal GiaBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
