//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaleFashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
        }
    
        public string MaSP { get; set; }
        public int MaTL { get; set; }
        public int MaNCC { get; set; }
        public string TenSP { get; set; }
        public decimal GiaBan { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public string HinhSP { get; set; }
        public Nullable<int> KichThuoc { get; set; }
        public string MauSac { get; set; }
        public string Mota { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public bool BanChay { get; set; }
        public bool PhoBien { get; set; }
        public bool Duyet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
